application: [APP ID HERE]
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin

- url: /.*
  script: sagittarius.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

env_variables:
  SAGITTARIUS_PASSWORD: [APP PASSWORD HERE]